spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=orderdb
    username: postgres
    password: Tuyen1234
    hikari:
      maxLifetime: '2000000'
      poolName: HikariPoolBooks
      connectionTimeout: '30000'
      idleTimeout: '30000'
      minimumIdle: '5'
      maximumPoolSize: '20'
  jpa:
    hibernate:
      use-new-id-generator-mappings: 'false'
#      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
app:
  kafka:
    order-topic: order.order-created
  async:
    core-pool-size: 20